### ISSUE TITLE
サービス概要決め

### ISSUE THREAD

**Issue by shizunaito** [pepabo-mobile-app-training/piyopiyo#1]
## サービス名
『ぴよぴよ』

## コンセプト
焚き火の火を見るようにフィードを眺めるアプリ

## ポイント
- フォローしていないユーザーのmicropostを見ることができる
- 可愛い

## 概要
- 全ユーザーのmicropostがランダムに流れる
- micropost主のプロフィールを見ることができる
- （Web上で）ユーザーのフィードにいける

## Prott
https://prottapp.com/app/#/projects/59c4ada04942fb38f7953a99

**Comment by piyoppi** [comment]
ユーザーテスト用prottはこちら
https://prottapp.com/p/52259f
