### ISSUE TITLE
第一回ユーザーテスト

### ISSUE THREAD

**Issue by shizunaito** [pepabo-mobile-app-training/piyopiyo#2]
## 対象
こうめいくん・えんどう

## テスト項目
- ログイン
- プロフィールの表示・キャンセル
- ユーザーフィードの表示

## シナリオ
このアプリでは誰かが呟いたツイートがランダムに流れていきます。

気になったツイートのツイート主のフィードを見に行ってください。
気になったツイートや思ったことは声に出してください。

## 質問
- 使っていて迷いはあったか
- 自由意見

**Comment by piyoppi** [comment]
テスト項目候補を考えてみる
- ログイン
- ユーザーフィードの表示

**Comment by shizunaito** [comment]
プロフィールの表示・キャンセル

**Comment by shizunaito** [comment]
## えんどう

#### 「もっと知りたい」が微妙
- 写真とかプロフィールとかが知れると思った
- 行きたいページと違うってなった

#### 「完了」ボタンで戻るのがわからなかった
- 右にスワイプとかがわかりやすいかも
- でもGmailのアプリでは「完了」押してた

#### ふきだしページ
- このページはなに？状態になる
- 吹き出しをタップする動作にたどり着くまですこし戸惑いがあった

**Comment by shizunaito** [comment]
## えんどう意見の対応

### ふきだしページ
- スプラッシュに書く？
  - 見ない
- **チュートリアルをおく！**
  - 一旦簡単に1枚にまとめる！

### 「もっと知りたい」が微妙
- ボタンの名前変えれば良いのでは？
  - つぶやきをもっと見る
  - **他のつぶやき**
  - もっとみる

### 「完了」ボタンで戻るのがわからなかった
一旦リアルWebViewで試してみる

**Comment by shizunaito** [comment]
## こーめいくん

チュートリアルがあってよかった

#### フィードもアプリ内で表示できるとなお良い
- WebViewの操作が微妙そうだった
  - 「完了」ボタン操作など

**Comment by shizunaito** [comment]
終わったのでCloseします！
