### ISSUE TITLE
シミュレータのアニメーションをgifにする

### ISSUE THREAD

**Issue by shizunaito** [pepabo-mobile-app-training/piyopiyo#24]
### 概要
Simulator上のアニメーションを録画して、gifに変換する方法

動きのあるUIを作った時のPRなどにはるとわかりやすくなりそうです。

#### 録画方法
1. 『Simulator』を起動しておく
1. 『QuickTime Player』を起動
1. 『ファイル』＞『新規画面収録』を選択
1. 下のウィンドウが表示されるので、録画ボタンを押して撮りたい画面をキャプチャする
<img width="295" alt="2017-09-28 15 57 00" src="https://user-images.githubusercontent.com/14357415/30953204-cd52a3d0-a465-11e7-81cd-125c475a22a9.png">

#### gifに変換する方法
1. ffmpegとgifsicleをhomebrewでインストールする
`brew install ffmpeg gifsicle`
1. 上記で録画したファイルを指定して、gifアニメーションに変換し出力する
`ffmpeg -i hoge.mov -r 10 -f gif - | gifsicle --delay=10 --optimize=3 > huga.gif`

**Comment by Fendo181** [comment]
@shizunaito 
共有ありがとう！
