### ISSUE TITLE
第二回ユーザーテスト

### ISSUE THREAD

**Issue by shizunaito** [pepabo-mobile-app-training/piyopiyo#44]
### 対象
- 遠藤

### テスト項目
- Tutorialからの開始
- プロフィールの表示・キャンセル
- ユーザーフィードの表示

#### 1
このアプリでは誰かが呟いたツイートがランダムに流れていきます。

気になったツイートのツイート主のフィードを見に行ってください。
気になったツイートや思ったことは声に出してください。

#### 2
気になったツイートのプロフィールをいくつか見てください。

### 質問
- 使っていて迷いはあったか
- 自由意見

**Comment by piyoppi** [comment]
チェックシート
### 1
- [ ] チュートリアル画面を閉じられているかどうか
- [ ] ふきだしをタップしたかどうか
- [ ] 「ほかのつぶやき」をタップしたかどうか

### 2
- [ ] ユーザープロフィールの表示を閉じられたかどうか
- [ ] ユーザーフィードの「Back」ボタンをタップしたかどうか

**Comment by piyoppi** [comment]
## えんどぅ
### 1
- [x] チュートリアル画面を閉じられているかどうか
- [x] ふきだしをタップしたかどうか
- [x] 「ほかのつぶやき」をタップしたかどうか

### 2
- [x] ユーザープロフィールの表示を閉じられたかどうか
- [x] ユーザーフィードの「Back」ボタンをタップしたかどうか  

### コメント
- ユーザープロフィールのXボタンが見つけられなかった
- ユーザープロフィールのアイコンをタップしたらユーザーフィードに行けると思っていた
- Twitterクライアントにしたら良さそう

**Comment by piyoppi** [comment]
## おかえり
### 1
- [x] チュートリアル画面を閉じられているかどうか
- [x] ふきだしをタップしたかどうか
- [x] 「ほかのつぶやき」をタップしたかどうか

### 2
- [x] ユーザープロフィールの表示を閉じられたかどうか
- [x] ユーザーフィードの「Back」ボタンをタップしたかどうか  

### コメント
- ランダムであることがわかりにくい
    - ふきだしの色とかが違うと異なるつぶやきであると分かりやすそう
    - ぱっと見全部一緒に見えてしまいそう
    - 名前が吹き出しに現れていないのはおもしろそう（どきどき）

**Comment by piyoppi** [comment]
## りえたむ

### 1
- [x] チュートリアル画面を閉じられているかどうか
- [x] ふきだしをタップしたかどうか
- [x] 「ほかのつぶやき」をタップしたかどうか

### 2
- [x] ユーザープロフィールの表示を閉じられたかどうか
- [x] ユーザーフィードの「Back」ボタンをタップしたかどうか  

- どこ押したらいいのかわからなかった
- チュートリアルを読まなかった
- もうちょっとひよこが **おおきい** ほうがいいかも
- 流れるのがはやいなーという気持ちがある
    - 勝手に流れるのはちょっと、という気持ちになった
    - ひよこを押したらふきだしがでてくるのが楽しいかも
    - 連打するとふきだしがたくさんでてくる
    - ふうせんがいい
    - カラフル
- 子ひよこが左下にいるといいかも
    - ひよこを押すとよろこぶ
    - 風船がとんでよろこぶ（子ひよこが）
    - ふきだししかないとさみしい
    - あひるでもいい
        - ひよこVSあひる
- ユーザープロフィール
    - 特に迷いはなし
    - 英語なのがきになる。。。
    - スクロール・一時停止
    - ひよこ押すととまる
        - 再生と停止ボタン
        - ひよこ押したくなる
    - 背景は白でない方がいい
        - しばふと子ひよことふうせん
        - ３体くらい（それ以上だと多い）
        -

**Comment by shizunaito** [comment]
終わったのでcloseします〜！
