### ISSUE TITLE
Twitterクライアント化に向けた調査

### ISSUE THREAD

**Issue by piyoppi** [pepabo-mobile-app-training/piyopiyo#55]
### 困っていること
- Twitterのつぶやきをひろってふきだしに表示するようにしたい

### ゴール
- APIの使い方がわかる
- Twitter API Clientをインストールして使い方がわかるようにする

**Comment by piyoppi** [comment]
とりあえず「TwitterKit」を導入する。
[TwitterKitのインストール](https://dev.twitter.com/twitterkit/ios/installation) ページを見ると、Carthageでの導入方法が紹介されていない（CocoaPodsの情報ならある）

**Comment by piyoppi** [comment]
ひとまず先ほどのページを参考に、マニュアルインストールの形で導入した
（CocoaPods導入は、テストスクリプトの見直しなども必要と考えられるので、ひとまず見送り）

**Comment by piyoppi** [comment]
Swiftならこのようなライブラリも存在する（ツイッター公式で紹介されている）
https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries
https://github.com/mattdonnelly/Swifter

**Comment by piyoppi** [comment]
ツイートをランダムに取得する `statuses/sample` は、ログインが必要っぽい
ref: https://developer.twitter.com/en/docs/tweets/sample-realtime/api-reference/get-statuses-sample

**Comment by piyoppi** [comment]
Swifterを入れてみたけど、ドキュメントがあまりないのがきになる。公式のTwitterKitと比較した方がいい可能性がある。

**Comment by piyoppi** [comment]
Swifterは認証時にSafariを呼んで、OAuth認証をしているっぽい。TwitterKitだとアプリ内で完結している（WebViewを呼んでいる）ので、TwitterKitのほうが画面遷移に違和感がない。

**Comment by shizunaito** [comment]
TwitterKitの方だと、streaming apiを叩くメソッドがないためその辺が全て独自実装になるのですが、少し時間をかけてもわからなそうでした…

なので、ひとまずはSwifterを使うことにします。

> Swifterは認証時にSafariを呼んで、OAuth認証をしているっぽい。

これに関しては、safariで開いてからカスタムURLスキームを使ってアプリに戻る実装にしました。

**Comment by shizunaito** [comment]
`streamRandomSampleTweets`でランダムにツイートが流れてくるようにはなった。
ただ、このメソッドだと`statuses/sample.json`を叩いていて、全てのツイートが取得されるので、色々な言語のツイートが流れて来てしまう。

APIの`statuses/filter.json`を叩く`postTweetFilters`メソッドを使ってlocationパラメータで日本を指定するのが良さそうという話になった。

**Comment by shizunaito** [comment]
`statuses/filter.json`で日本の最西端と最北端の経度緯度を指定するとほぼ日本語のツイートになった（たまに中国語と韓国語あり）！！

ストリーミングなのでこのままだと永遠に流れて来てしまうため、止められるようにする。

**Comment by shizunaito** [comment]
### 止まらない問題
`swifter.streamRandomSampleTweets`を保存して置く`HTTPRequest`のプロパティを用意し、そこに入れておく。
そのプロパティを使って止めたいタイミングで`sample.stop()`を呼び出すと止めることができる。

### 日本語問題
`streamRandomSampleTweets`に`language`というパラメータがあり、`["ja"]`と指定すると日本語のツイートのみ取得できたのでそれを使う。

**Comment by shizunaito** [comment]
Swifterを使ってTweetを取得できたので閉じます
