### ISSUE TITLE
リリースに必要な情報の調査・まとめ

### ISSUE THREAD

**Issue by shizunaito** [pepabo-mobile-app-training/piyopiyo#74]
### 困っていること
そろそろリリースが現実的になってきたので、申請に必要な情報を調べてまとめます。

### ゴール
Appleの申請が通る

### 関係者
@piyoppi

**Comment by shizunaito** [comment]
## 準備するもの
### App情報
- [x] 名前：Appstoreに表示される名前
- [x] プライバシーポリシーURL（とりあえずgithub）
- [x] サブタイトル（optional）：Appstoreで名前の下に表示される概要
- [ ] カテゴリ：このアプリのカテゴリ（選択形式）

### バージョン情報
- [x] スクリーンショット：アプリのスクリーンショット。JPGもしくはPNG。
- [x] 概要：Appに関する説明。
- [x] キーワード：検索用キーワード
- [x] サポートURL：サポート用のWebページ（とりあえずgithub）

### App一般情報
- [x] アイコン：1024 * 1024
- [x] バージョン
- [x] Copyright
- [x] App Reviewに関する情報
  - [x] 連絡先
  - [x] メモ：審査で必要な情報があれば記入。

#### 申請の参考になりそうなサイト
[iTunes Connect ワークフロー](https://help.apple.com/itunes-connect/developer/#/dev300c2c5bf)
[[iPhone] iOSアプリを登録、申請して公開するまで](https://i-app-tec.com/ios/app-release.html)
[[iPhone] iTunes Connect にアプリ情報を登録して申請する](https://i-app-tec.com/ios/itunes-connect.html)

**Comment by piyoppi** [comment]
アプリのバージョン情報
- 連絡が取れるリンクを貼る
- バージョンナンバーとアプリ名

**Comment by shizunaito** [comment]
store申請で使うイメージ画像

サイズ：414x736

<img width="335" alt="app_image01" src="https://user-images.githubusercontent.com/14357415/31883338-89937390-b824-11e7-9656-89eb8dc38ac9.png">
<img width="337" alt="app_image02" src="https://user-images.githubusercontent.com/14357415/31883339-89baee70-b824-11e7-9a12-d89e143ac31c.png">

**Comment by piyoppi** [comment]
![scr1](https://user-images.githubusercontent.com/19523490/31929215-103207d4-b8d6-11e7-812f-f965ef2aada1.png)
![scr2](https://user-images.githubusercontent.com/19523490/31929216-11bf0476-b8d6-11e7-9921-a34d14cf69b7.png)

**Comment by piyoppi** [comment]
![scr1x2](https://user-images.githubusercontent.com/19523490/31929428-f3aa74ce-b8d6-11e7-9e84-d894035a995b.png)
![scr2x2](https://user-images.githubusercontent.com/19523490/31929429-f3e20ab0-b8d6-11e7-8eda-86916f81a38c.png)

**Comment by piyoppi** [comment]
![scr1x3](https://user-images.githubusercontent.com/19523490/31929496-47f65ec6-b8d7-11e7-91b4-fad258d46182.png)
![scr2x3](https://user-images.githubusercontent.com/19523490/31929497-48198cc0-b8d7-11e7-8521-758079462c3c.png)

**Comment by piyoppi** [comment]
<img width="1024" alt="ipad_scr1" src="https://user-images.githubusercontent.com/19523490/31982766-3971d01a-b995-11e7-972a-d3c1f361632b.png">

**Comment by piyoppi** [comment]
![ipad_scr2](https://user-images.githubusercontent.com/19523490/31982780-4b64455a-b995-11e7-8a27-51a84790e867.png)
